### ISSUE TITLE
is there anyway to support multiple re-useable cell?

### ISSUE THREAD

**Issue by alexzzp** [jessesquires/JSQDataSourcesKit#10]

**Comment by alexzzp** [comment]
I have tried to modify the code to support multiple cell:

"""
    public func cellForItem(item: DataItem, inTableView tableView: UITableView, atIndexPath indexPath: NSIndexPath) -> Cell? {
        if self.reuseIdentifier == "" {
            return nil
        } else {
            return tableView.dequeueReusableCellWithIdentifier(reuseIdentifier, forIndexPath: indexPath) as? Cell
        }
    }
"""

"""
// create factory
        let factory = TableViewCellFactory(reuseIdentifier: "") { (cell: UITableViewCell?, model: Owner, tableView: UITableView, indexPath: NSIndexPath) -> UITableViewCell in
            let owner = model
            if owner.name == TFCommon.newCellIdent {
                let reuseCell = tableView.dequeueReusableCellWithIdentifier(ident1) as! TFCell1
                return reuseCell
            } else {
                let reuseCell = tableView.dequeueReusableCellWithIdentifier(ident2)  as! TFCell2  
                return reuseCell
            }
        }
"""

**Comment by jessesquires** [comment]
hey @alexzzp, the way to do this would be to make a "ComposedFactory" — a factory that contains other specific factories.

There's a small example in the demo:
https://github.com/jessesquires/JSQDataSourcesKit/blob/develop/Example/Example/ComposedSupplementaryViewFactory.swift

If you're having trouble with types, consider using a protocol or a common superclass.

**Comment by alexzzp** [comment]
thanks, I will have a try
