### ISSUE TITLE
Setup Danger

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQDataSourcesKit#107]
Need to:

- update `.travis.yml`
- add `Dangerfile`
- add `Gemfile`

basic example:
https://github.com/SwiftWeekly/swiftweekly.github.io/commit/2e4da931cc074918c767e19320757d58be4a5018#diff-16417461de376720abfe05ef4cb7d73a

**Comment by kevnm67** [comment]
@jessesquires Do you want help setting up danger?

**Comment by jessesquires** [comment]
@kevnm67 sure! that would be awesome.

i just updated the original issue description with what needs to happen.

i've already got a bot + token setup. once we have a PR, i can update travis-ci.

**Comment by kevnm67** [comment]
@jessesquires 👍 

Two questions for you:

1. Could you add the token as a private environment variable on travisci.com as ```DANGER_GITHUB_API_TOKEN```
<img width="831" alt="image" src="https://user-images.githubusercontent.com/2734154/53960319-fb3e5280-40b3-11e9-8407-43ed6d0be3bb.png">

2. Any preference on danger ruby vs. swift?

**Comment by jessesquires** [comment]
@kevnm67 

1. done ✅ 
2. ruby -- looks like that's what you used in  #120 👍

**Comment by jessesquires** [comment]
closed by #120
