### ISSUE TITLE
FetchedResultsDelegate is called from a background thread

### ISSUE THREAD

**Issue by MaorS** [jessesquires/JSQDataSourcesKit#115]
## General information

- Library version: 7
- OS version: 10.14.2
- Devices/Simulators: iPhone 6S Plus
- Reproducible in the demo project (Yes/**No**): 
- Any related issues:

## What happened?

I'm using fetchedResultsController with private context because my project is using a-lot of media and display them as a gallery. ( when changing to main context the app freeze)

So i get warnings like " Main Thread Checker: UI API called on a background thread:  -[UICollectionView performBatchUpdates:completion:]

<img width="1253" alt="screen shot 2019-02-01 at 18 00 16" src="https://user-images.githubusercontent.com/20594674/52135804-4f868a80-264f-11e9-840f-65b4cb8d2681.png">

**Comment by jessesquires** [comment]
Thanks @MaorS ! 

These delegate methods should be called on the main thread. Anything UI related in your app should be using a main thread ManagedObjectContext.

Can you explain more about the context in which you are using them and how they are getting called from a background thread? Can you provide the code snippets of the caller?
