### ISSUE TITLE
Update CocoaPods

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQDataSourcesKit#118]
New swift versions:
http://blog.cocoapods.org/CocoaPods-1.7.0-beta/

Test specs?
http://blog.cocoapods.org/CocoaPods-1.3.0/

**Comment by kevnm67** [comment]
@jessesquires Are you familiar with [dependabot](https://github.com/marketplace/dependabot-preview)? Github recently acquired them and it's now free.  Worth checking out.

**Comment by jessesquires** [comment]
ah yes -- but that's only for automated security fixes, right? (which i have turned on)

**Comment by jessesquires** [comment]
that is, the integration with GH currently.

or is there a setting to always update dependencies to the latest version?

**Comment by kevnm67** [comment]
@jessesquires The bot creates individual PR's for outdated dependencies.  It's not limited to security fixes.  

Here's an [example](https://github.com/kevnm67/danger-pivotal_tracker/pull/12).

**Comment by jessesquires** [comment]
oh, that's awesome.

how do you enable this?

**Comment by jessesquires** [comment]
oh nevermind. found it.

**Comment by kevnm67** [comment]
@jessesquires I was about to respond 🤣
