### ISSUE TITLE
Compile errors on swift 2.0 Xcode 7

### ISSUE THREAD

**Issue by LeeMatthewHiggins** [jessesquires/JSQDataSourcesKit#18]
JSQDataSourcesKit/JSQDataSourcesKit/JSQDataSourcesKit/FetchedResultsDelegate.swift:246:21: Type 'BridgedFetchedResultsDelegate' does not conform to protocol 'NSObjectProtocol'

JSQDataSourcesKit/JSQDataSourcesKit/JSQDataSourcesKit/FetchedResultsDelegate.swift:278:16: Objective-C method 'controller:didChangeObject:atIndexPath:forChangeType:newIndexPath:' provided by method 'controller(_:didChangeObject:atIndexPath:forChangeType:newIndexPath:)' conflicts with optional requirement method 'controller(_:didChangeObject:atIndexPath:forChangeType:newIndexPath:)' in protocol 'NSFetchedResultsControllerDelegate'

JSQDataSourcesKit/JSQDataSourcesKit/JSQDataSourcesKit/CollectionViewDataSource.swift:439:80: Downcast from 'NSFetchedResultsSectionInfo?' to 'NSFetchedResultsSectionInfo' only unwraps optionals; did you mean to use '!'?

JSQDataSourcesKit/JSQDataSourcesKit/JSQDataSourcesKit/TableViewDataSource.swift:321:80: Downcast from 'NSFetchedResultsSectionInfo?' to 'NSFetchedResultsSectionInfo' only unwraps optionals; did you mean to use '!'?

JSQDataSourcesKit/JSQDataSourcesKit/JSQDataSourcesKit/TableViewDataSource.swift:330:80: Downcast from 'NSFetchedResultsSectionInfo?' to 'NSFetchedResultsSectionInfo' only unwraps optionals; did you mean to use '!'?

**Comment by jessesquires** [comment]
Thanks @LeeMatthewHiggins !

This is fixed on `develop` and will be available with the 2.0 release — coming soon!
