### ISSUE TITLE
Very nasty apple bug in FRC delegate callback on IOS9!

### ISSUE THREAD

**Issue by LeeMatthewHiggins** [jessesquires/JSQDataSourcesKit#19]
In the CollectionViewFetchedResultsDelegateProvider I had some very nasty crash problems with updates from FRC on IOS9 SDK running on 8.4 SDK device. I have tracked down to an apple bug, an invalid change type sent on delegate callbacks, I hacked a fix here....

line 74 in  fetchedResultsDelegate.swift

```
 didChangeObject: { [unowned self] (controller, anyObject, indexPath: NSIndexPath?, changeType, newIndexPath: NSIndexPath?) -> Void in
            var changes = ObjectChangesDictionary()
            let checkInt = changeType.rawValue //nasty calls from apple have invalid changeTypes in ios9!!!!

            if (checkInt>0) {

                switch changeType {
                case .Update:
                    if let i = indexPath {
                        changes[changeType] = [i]
                    }
                case .Insert:
                    if let insertIndexPath = newIndexPath {
                        changes[changeType] = [insertIndexPath]
                    }
                case .Delete:
                    if let deleteIndexPath = indexPath {
                        changes[changeType] = [deleteIndexPath]
                    }
                case .Move:
                    if let old = indexPath, new = newIndexPath {
                        changes[changeType] = [old, new]
                    }
                }

                self.objectChanges.append(changes)
            }
        },
```

**Comment by jessesquires** [comment]
Thanks @LeeMatthewHiggins ! :+1:  Will get this fixed for 2.0

**Comment by jessesquires** [comment]
Hey @LeeMatthewHiggins -- been testing most of the day. Getting ready to ship `v2.0`. I still haven't ben able to reproduce this.

Can you provide anymore info or a demo project?

**Comment by jessesquires** [comment]
@LeeMatthewHiggins -- a lot changed and improved in this area for `v2.0`. Are you still seeing this bug?

I've tested on 8.4 simulator, but still haven't see it. Unfortunately, I don't have an 8.4 device right now...

Going to close this for now. Let me know if I should re-open! :smile:
