### ISSUE TITLE
UI Tests for Example project

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQDataSourcesKit#27]
Use Xcode's UI testing. 
- https://www.bignerdranch.com/blog/ui-testing-in-xcode-7-part-1-ui-testing-gotchas/
- https://developer.apple.com/library/ios/documentation/ToolsLanguages/Conceptual/Xcode_Overview/RecordingUITests.html
- https://developer.apple.com/videos/play/wwdc2015/406/

**Comment by broadwaylamb** [comment]
Do you need any help with this issue? What aspects should be tested?

I'd be glad to contribute.

**Comment by jessesquires** [comment]
Thanks @broadwaylamb ! 

I just pushed some changes to the example to organize it better. There's an empty UITesting bundle there now too, so all you need to do is record some tests and push.

Things to test:
- For initial view and static table/collection views, we can just test the basics of the view, that the expected cells appear.
- For the fetched results table/collection view, we can test that adding/deleting items adds/removes cells. Testing the other aspects might be difficult since the example app is currently random when adding/changing cells. We can address that later, in a separate PR.
