### ISSUE TITLE
Cannot convert value of type '[MyType]' to expected argument type '[_]'

### ISSUE THREAD

**Issue by yoiang** [jessesquires/JSQDataSourcesKit#33]
Hey @jessesquires, the library looks great, I'm excited to try it out!

When I compose the below I get the compiler error `Cannot convert value of type '[MyType]' to expected argument type '[_]'`:

``` swift
    let sections = [TableViewSection<MyType>(items: viewModel.items)]
```

If I switch to the below and let Swift assume the generic's type it goes away:

``` swift
    let sections = [TableViewSection(items: viewModel.items)]
```

But then when I try to compose the Data Source Provider I get the error again, this time on the `sections` parameter:

``` swift
    typealias ListSection = TableViewSection<MyType>
    typealias ListCellFactory = TableViewCellFactory<MyTypeViewCell, MyType>
    private var listDataSourceProvider : TableViewDataSourceProvider<ListSection, ListCellFactory>?

    let listCellFactory = ListCellFactory(reuseIdentifier: "MyCell", cellConfigurator: { (cell : MyTypeViewCell, model, tableView, indexPath) -> MyTypeViewCell in
        ...
        return cell
    })
    self.listDataSourceProvider = TableViewDataSourceProvider<ListSection, ListCellFactory>(sections: sections, cellFactory: self.listCellFactory, tableView: list)
```

If I don't specify a type for TableViewSection as the SectionInfo type it complains `Reference to generic type "MyType" requires arguments in <...>'

I wish I could help diagnose more but my lack of experience with generics in Swift is obvious.

Thanks for your help!

**Comment by jessesquires** [comment]
Hey @yoiang! :smile: 

In your `cellConfigurator`, specify the model type:

``` swift
cellConfigurator: { (cell: MyTypeViewCell, model: MyType, tableView, indexPath) -> MyTypeViewCell in
```

That should give Swift all the information it needs. Let me know if this doesn't fix it!

---

Also, I think you can remove the type params from the data source init and simply use `TableViewDataSourceProvider(sections: ...)`

**Comment by yoiang** [comment]
Hey @jessesquires!
Thanks for the quick response, sorry for my late response!

That didn't do it buuuuut...switching

``` swift
let sections = [TableViewSection(items: viewModel.items)]
```

to

``` swift
let sections = [TableViewSection(viewModel.items)]
```

did it. If it wasn't clear (and it probably wasn't, I didn't mention above), viewModel.items is an array of my item type instances. I was confusing Swift and it wasn't knowledgable enough to say so. My original declaration was putting forward for the TableViewSection that each individual item was an array type. Once I realized TableViewSection has a variable argument and an array argument init it was a quick realization.

**Comment by jessesquires** [comment]
@yoiang -- Ah, I see :smile: Thanks for the update! :+1: 

If you run into any other problems, please open another issue!
