### ISSUE TITLE
Crash from String(reflecting: Item.self) assert when model class is in app module

### ISSUE THREAD

**Issue by bonebox** [jessesquires/JSQDataSourcesKit#34]
This method in the assert calls is causing my app to crash, because it's returning a namespaced string for my manage object (ie. "ModuleName.ClassName") from which NSClassFromString isn't able to create a class, thus returning nil.  This causes `fatal error: unexpectedly found nil while unwrapping an Optional value` in line 30 of Internal.swift.  Substituting String(Item.self) instead only returns the class name and works as expected.

**Comment by jessesquires** [comment]
Thanks @bonebox !

Can you provide more information about what you're trying to do?

**Comment by bonebox** [comment]
Basically I copied most of `FetchedCollectionViewController.swift` in your Example project but substituted my own classes where necessary (for the cell and managed object).  I get the error when creating the instances for `CollectionViewFetchedResultsDelegateProvider` and `CollectionViewFetchedResultsDataSourceProvider` where the `assert` is called, because of what I outlined previously.  As mentioned, changing it to `String(Item.self)` instead of `String(reflecting: Item.self)` in the respective initializers for those classes fixes the issue for me.  Let me know if there's anything specific you're wanting to know.  Thanks!

**Comment by jessesquires** [comment]
Hm... So what's your class for `CellFactory.Item` and what class of objects does your `NSFetchedResultsController` fetch? 
- Are they the same?
- Are they `NSManagedObject` subclasses?
- Are they in the same module?
- Are they in a framework module, or your main app module?

Can you provide an example project that shows the issue?

**Comment by bonebox** [comment]
Both the CellFactory.Item and the NSFetchedResultsController are using the same class, which is a standard NSManagedObject subclass.  The class is in the main app module.  The name of the class is `Session`, and the app is called `Breather`.  

The compare between the fetchedClass and expectedClass isn't even being reached anyway, as the crash is occurring with this line: `let expectedClass: AnyClass = NSClassFromString(className)!` in `Internal.swift`.  The problem, as mentioned, is that `className` being used here includes the module name (so the string is `Breather.Session`) and `NSClassFromString:` apparently doesn't like this so returns `nil` which in turn causes a crash with the forced unwrap.  

Changing the `String(reflecting: Item.self)` lines to `String(Item.self)` works because it returns only the class name (`Session`), which allows `NSClassFromString:` to successfully create the class.  Then the assert is successful.

**Comment by jessesquires** [comment]
Thanks @bonebox !

I think the issue is that your class is in your main app module.

If you look at the demo app, it does not have this problem. This is probably because it has a separate framework for the model, and thus a fully-qualified name. This is why I missed the bug during development.

---

#### Proposed solution

Check `String(reflecting:` first, then fallback to `String()` if the former is `nil`.

---

By the way, I highly recommend putting your CoreData model in its own framework. This is very convenient/useful for lots of reasons. :smile:

**Comment by jessesquires** [comment]
Also, this might be a Swift bug.

**Comment by bonebox** [comment]
Thanks for looking at this!  I do see how it would work if the Core Data model were in a separate framework.  I do this for reusable frameworks, but for this particular app didn't feel it was necessary as the app is pretty specific.  Also, in my experience, quite a few developers have their model in the main app bundle, so I imagine this will affect more people down the road.  

I think your proposed solution is a good one, however I wanted to clarify that `String(reflecting: )` isn't `nil` in my case--it returns the fully-qualified name.  So perhaps instead, rather than force unwrapping the `NSClassFromString`, you would check if that returns nil, and then do the `String(instance: )` as a fallback.

**Comment by bonebox** [comment]
Very well could be a Swift bug, seems like I find a new one every day... :persevere:

**Comment by jessesquires** [comment]
Ah, right. Thanks @bonebox ! :+1:

**Comment by jessesquires** [comment]
Hey @bonebox - fix is now in `develop`. You can pull from there directly until the official `3.0.1` release.

Let me know if you have any other issues! :smile:

**Comment by bonebox** [comment]
Looks good, thanks!
