### ISSUE TITLE
Different cell styles for each section

### ISSUE THREAD

**Issue by yimingtang** [jessesquires/JSQDataSourcesKit#35]
Hi, Jesse.

I'm developing a similar library in Objective-C. In my project, I came across a problem. **What if I want to apply different cell styles to each section?** JSQDataSourcesKit is based on the assumption that the cell style is always the same throughout the UITableView or UICollectionView, because the data source provider has only **one** `cellFactory` object.

Let's take a look at App Store.app. The home page (a.k.a. Featured) is a complex collection view. It has several sections. Each section has its own cell style. The whole page is dynamic and data-driven. Obviously, the original implementation won't meet this kind of requirement.

A simple solution is to move `cellFactory` into sections, since in most cases, the cell style won't change in the same section.

Please let me know if you have any ideas about this issue.

**Comment by jessesquires** [comment]
Hey @yimingtang ! :smile: 

This is possible in the library. You can achieve this by composing factories.
1. Create CellAFactory 
2. Create CellBFactory
3. Create ComposedCellFactory (type of cell will be `UITableViewCell` or `UICollectionViewCell`)

The ComposedCellFactory will also conform to the factory protocol, and internally forward control to either CellAFactory or CellBFactory.

The demo has an example of this pattern here: https://github.com/jessesquires/JSQDataSourcesKit/blob/develop/Example/Example/ComposedSupplementaryViewFactory.swift

For cells, you'll need to cast from your specific cell subclass to `UITableViewCell`/`UICollectionViewCell` inside the ComposedFactory instance when you return it, but this is a safe cast (simply going from subclass to superclass).

**Comment by jessesquires** [comment]
> A simple solution is to move `cellFactory` into sections, since in most cases, the cell style won't change in the same section.

Interesting idea. But would each section have different models? If so, this will be cumbersome to express in Swift. Admittedly, the "ComposedCellFactory" pattern could also get out of hand depending on your design, but that may be indicative of deeper design problems.

One strategy for unifying models (generally, but specifically for the composition pattern), would be to use protocols. Or, you could map `N` model types to 1 ViewModel type if your design permits.

**Comment by jessesquires** [comment]
Oh -- one more thing.

This is probably a last resort, but you could always use `<Any, MyCell>` as parameters and cast everything as needed. Probably not a good design though -- I wouldn't recommend this.

**Comment by yimingtang** [comment]
Thank you for your suggestions, @jessesquires !
