### ISSUE TITLE
Problem with adding TitledCollectionReusableViewFactory to CollectionViewFetchedResultsDataSourceProvider

### ISSUE THREAD

**Issue by bonebox** [jessesquires/JSQDataSourcesKit#36]
I'm following your example in `FetchedCollectionViewController.swift` except that I only want to have a section header (no footer).  So I'm creating a `TitledCollectionReusableViewFactory` instance and trying to add that as the `supplementaryViewFactory` to the `CollectionViewFetchedResultsDataSourceProvider` initializer (instead of using `ComposedSupplementaryViewFactory` like in your example--that class isn't included in the CocoaPod, btw).   However Xcode won't allow this, giving the error:

`Cannot convert value of type 'TitledCollectionReusableViewFactory<Session>' to expected argument type '_?'`

The `Session` is my managed object. Everything else is setup the same way as in your example.

**Comment by bonebox** [comment]
Never mind, I realized I needed to create a custom factory class similar to `ComposedSupplementaryViewFactory` and add the `TitledCollectionReusableViewFactory` instance to it, then use that in the `CollectionViewFetchedResultsDataSourceProvider` initializer.

**Comment by jessesquires** [comment]
Thanks @bonebox ! :smile: 

Let me know if anything else comes up!
