### ISSUE TITLE
tvOS

### ISSUE THREAD

**Issue by f1nality** [jessesquires/JSQDataSourcesKit#37]
Hello,
Can this library be used for tvOS?

Thanks

**Comment by jessesquires** [comment]
Hey @f1nality ! :smile: 

Yep! You shouldn't have any problems. There isn't an explicit tvOS target in the framework yet (and the podspec doesn't specify tvOS support), but it should work.

I'll add this explicitly this week. See #39

**Comment by f1nality** [comment]
Hello, @jessesquires!

That's great, thank you.
