### ISSUE TITLE
NSFetchRequest with fetchLimit causes crash

### ISSUE THREAD

**Issue by f1nality** [jessesquires/JSQDataSourcesKit#40]
Hello,
Using NSFetchRequest with fetchLimit cases crash if objects are added to managed context. This happens because  `(self.fetchedResultsController.sections?[section])?.numberOfObjects ?? 0` (CollectionViewDataSourceProvider.swift line 236) returns more objects than `fetchLimit` is (discussed http://stackoverflow.com/questions/9022580/nsfetchedresultscontroller-ignores-fetchlimit-after-performfetch). So first of all collectionview begins to render more cells than `fetchLimit` and after another `performFetch` it crashes as dataSource tries to get section item with index > `fetchLimit`.

Ability to override `bridgedDataSource`'s `numberOfItemsInSection` will fix this problem.

**Comment by f1nality** [comment]
> Ability to override bridgedDataSource's numberOfItemsInSection will fix this problem.

But it's not enough. `CollectionViewFetchedResultsDelegateProvider`'s `BridgedFetchedResultsDelegate` also receives updates with `indexPath.row` > `fetchLimit`

**Comment by jessesquires** [comment]
Thanks @f1nality !

I'm not sure about this. I've never seen such an issue...

**Comment by jessesquires** [comment]
Can you reproduce this in the demo?

**Comment by f1nality** [comment]
Yes, i'll post it later

**Comment by jessesquires** [comment]
Hey @f1nality — I was able to reproduce in the example app, but only with the `tableview` example, not the `collectionView`.

Steps:
1. Set a `fetchLimit` of 10 [here](https://github.com/jessesquires/JSQDataSourcesKit/blob/develop/Example/Example/Thing.swift#L108)
2. Run example app, hit `+` button a few times (adds 5 items each time)
3. Push table view fetched results example
4. Delete items in the table view such that a section will be removed
5. Crash

The initial fetch was fine. No crashes, and it correctly displayed the first 10 items.

For the collection view example, repeatedly deleting items re-fetched such that there were always 10 items (unless there were less than 10) — which is likely a side-effect of [this](https://github.com/jessesquires/JSQDataSourcesKit/blob/develop/JSQDataSourcesKit/JSQDataSourcesKit/FetchedResultsDelegate.swift#L180-L184).

**Comment by jessesquires** [comment]
So, it looks like the core of the problem is:
1. Setting a `fetchLimit`
2. And then mutating your dataset (deleting/inserting items)

**Comment by f1nality** [comment]
@jessesquires 
Yeap, if need exactly collectionview example - let me know.

**Comment by jessesquires** [comment]
@f1nality -- please! :grin: 

What if you mutate data, then performFetch and reloadData?

**Comment by jessesquires** [comment]
Maybe related?
http://stackoverflow.com/questions/11365589/batch-size-does-not-work-when-using-parent-child-contexts

**Comment by jessesquires** [comment]
Still never able to repro this and we don't have further info to suggest that it's actually *caused by this library*. 

Going to close for now.
