### ISSUE TITLE
Declared closure result 'UICollectionViewCell' is incompatible with contextual type '_'

### ISSUE THREAD

**Issue by hokster7** [jessesquires/JSQDataSourcesKit#41]
This error doesn't make much sense to me:

![screen shot 2015-12-19 at 16 19 36](https://cloud.githubusercontent.com/assets/430233/11913947/534ea9ce-a66c-11e5-92f0-24c64c04a850.png)

**Comment by jessesquires** [comment]
Hey @fatuhoku :smile:  It looks like swift can't infer the type of cell, or you are returning the wrong cell type.

You should probably be returning your custom cell subclass here, not `UICollectionViewCell`

**Comment by hokster7** [comment]
What's a contextual type? :/

**Comment by jessesquires** [comment]
Ha, sometimes Swift error messages are not that great.

I think what this is trying to say is that Swift cannot infer the correct type, or there are mismatched types, given the current context.
