### ISSUE TITLE
Cannot convert value of type `[ CollectionViewSection<Int> ]` to expected argument type `[_]`

### ISSUE THREAD

**Issue by hokster7** [jessesquires/JSQDataSourcesKit#42]
![screen shot 2015-12-19 at 18 07 37](https://cloud.githubusercontent.com/assets/430233/11914524/6e04d306-a67b-11e5-8cf3-18725871b0f1.png)

I _really_ can't make sense of this error. It worked with `String`, but when I switched to using `Int` as a type this sort of compile error appears.

**Comment by jessesquires** [comment]
Hey @fatuhoku 

Here:

``` swift
// 3. create cell factory
```

You're still using `String` :smile:

**Comment by jessesquires** [comment]
Also, in the future, it's easier to help if you paste the code in your issue instead of a screenshot. :smile: 

You can create highlighted code blocks like this:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by hokster7** [comment]
@jessesquires Thanks, I'm aware of that already — I chose to use screenshots because you have the benefit of seeing where exactly the error is appearing on Xcode (at the expense of searchability), something you can't do easily with syntax highlighted code.

Damn, I should have figured that one out! I'm really amazed at how uninformative Swift errors are...
