### ISSUE TITLE
Using in tandem with JSQMessagesViewController

### ISSUE THREAD

**Issue by david-hoze** [jessesquires/JSQDataSourcesKit#47]
Hi :smile:,

I want to use `CollectionViewFetchedResultsDelegateProvider` with JSQMessagesViewController, but I can't implement the `cellConfigurator` for `CollectionViewCellFactory(reuseIdentifier:cellConfigurator:)`, since `JSQMessagesViewController` implements `collectionView(collectionView:cellForItemAtIndexPath:)` without using some `configureCell` method which I can call..

I implemented a [A standalone FetchedResultsDelegate](https://gist.github.com/amitai-hoze/8f0e8fab6f644025ebd813bbaaf99a87) so it can work without being coupled to the data source. Is there a better solution?

**Comment by jessesquires** [comment]
Hey, thanks @amitai-hoze ! :smile: 

Right, this is currently not possible in `JSQMessagesViewController`. However, the 8.0 release of the library will address these shortcomings. 

https://github.com/jessesquires/JSQMessagesViewController/issues/1216
