### ISSUE TITLE
Mixing cell and header types within a UICollectionView

### ISSUE THREAD

**Issue by dcaunt** [jessesquires/JSQDataSourcesKit#57]
I have a collection view with two sections, where each section uses a different `UICollectionReusableView` subclass for the header supplementary view. In the second section, I have two different `UICollectionViewCell` subclasses for different cell types. 

In trying to use `DataSourceProvider` I have failed in a couple of places. I looked at the approach taken in the Example's `ComposedCollectionSupplementaryViewFactory`, however this only deals with homogenous supplementary views (of type `TitledSupplementaryView`) and casting is required in the composite implementation of `configure` to convert the view to the correct type. I have a similar problem for my `ViewFactory`.

Further, the requirement of a single `Item` type is making it difficult to model the data for four different `UIView`s. 

Is what I'm trying to do beyond the scope of this library?

I have a feeling I'm missing something here and would appreciate some pointers. Thank you.

**Comment by jessesquires** [comment]
Hey @dcaunt ! 😄 

> Is what I'm trying to do beyond the scope of this library?

_Kind of_. Once you start introducing homogenous types, this library can become difficult to use. However, you can achieve this. A few possible strategies:
1. The easiest/simplest (cleanest?) way to do this would be to make your generic parameters `<Any, UICollectionViewCell>`, then simply cast inside of your `ViewFactory`, based on the index path. I just pushed a quick example that edits the demo to show this: 178d9c6781399cad5088ade6227d53018367874c 
2. You could find a way to treat your `Item` types heterogeneously, either via a protocol, type erasure, or view model layer — this really depends on your situation. 
3. You can combine (1) with a ComposedFactory, where the outermost factory uses `<Any, UICollectionViewCell>` and you cast internally on [the switch](https://github.com/jessesquires/JSQDataSourcesKit/blob/develop/Example/Sources/ComposedSupplementaryViewFactory.swift#L49-L52).

With (1), you loose type-safety to a certain degree, but if you know what your types are at each `IndexPath`, then the casting shouldn't be too risky. 

Also, the provided `ViewFactory` is pretty naive and is intended just to produce a single type of cell, as `reuseIdentiferFor(item: , type:, indexPath:)` just returns the single `reuseIdentifier` that you initialized it with. However, this is why the other components of the library only talk to `ReusableViewFactoryProtocol` — so you can easily build your own `ViewFactory` to vend multiple types of cells. 

---

Having said that, I'm open to any feedback on how we could make any of this better! 👍

**Comment by dcaunt** [comment]
@jessesquires thanks so much for the detailed response, I had a few ideas but this gives me more to go on. 

I'll have a play around with this in a sample project and publish it if I make any meaningful progress. At this point type erasure feels like it's going to get me furthest, but we'll see.

**Comment by jessesquires** [comment]
Oh, I just had another idea — you could use an enum for your models. This would make it really easy to have homogenous data over each section. _And_ you wouldn't have to cast the models, just the cells.

``` swift
enum ViewData {
    case section0(ModelA)
    case section1(ModelB)
    case section2(ModelC)
}
```

**Comment by dcaunt** [comment]
Thanks for the suggestion, using an enum for models is _roughly_ what I was working with when I opened the issue actually, and it seems that you're right about the casting. I need to clean it up a bit but I'm going to push a modified Example that you can look at, and perhaps it would be worth making a PR for this repo.

**Comment by jessesquires** [comment]
@dcaunt - cool!

For a PR, `develop` is Swift 2.2, then there's a `swift2.3` and `swift3.0` branch
