### ISSUE TITLE
Enhancement: DataSourceProtocol for existing NSFetchedResultsController

### ISSUE THREAD

**Issue by colinmorelli** [jessesquires/JSQDataSourcesKit#63]
Previous user of 3.x here - I'm a huge fan of the improvements you've brought to 4. However, I'm facing an issue using the FetchedResultsController with an _existing_ FRC. My app uses CoreStore (great CoreData wrapper btw). However, it masks most of the details of NSManagedObjectContext, preferring you to work through the APIs it provides. As a result, there's really no way to create a FRC without going through the library where it will return you one that's already built. However, in JSQ, the FRC implementation of the DataSourceProtocol subclasses the FRC and creates a new one.

I'm thinking the existing implementation could just be replaced with the code below, which both preserves the existing functionality and allows users to provide their own FRC. Thoughts?

```
public class FetchedResultsController<T: NSManagedObject> {

    private let fetchedResultsController: NSFetchedResultsController

    public init(fetchedResultsController: NSFetchedResultsController) {
      self.fetchedResultsController = fetchedResultsController
    }

    public convenience init(fetchRequest: NSFetchRequest,
                         managedObjectContext context: NSManagedObjectContext,
                                              sectionNameKeyPath: String?,
                                              cacheName name: String?) {
      self.init(fetchedResultsController: NSFetchedResultsController(
          fetchRequest: fetchRequest,
                   managedObjectContext: context,
                   sectionNameKeyPath: sectionNameKeyPath,
                   cacheName: name))
    }

    /**
     - parameter indexPath: The index path of an object.
     - returns: The object at `indexPath`.
     */
    public subscript (indexPath: NSIndexPath) -> T {
        get {
          return self.fetchedResultsController.objectAtIndexPath(indexPath) as! T
        }
    }
}


extension FetchedResultsController: DataSourceProtocol {
    /// :nodoc:
    public typealias Item = T

    /// :nodoc:
    public func numberOfSections() -> Int {
        return self.fetchedResultsController.sections?.count ?? 0
    }

    /// :nodoc:
    public func numberOfItems(inSection section: Int) -> Int {
        guard section < numberOfSections() else { return 0 }
        return self.fetchedResultsController.sections?[section].numberOfObjects ?? 0
    }

    /// :nodoc:
    public func items(inSection section: Int) -> [Item]? {
        guard section < numberOfSections() else { return nil }
        return (self.fetchedResultsController.sections?[section].objects as! [Item])
    }

    /// :nodoc:
    public func item(atRow row: Int, inSection section: Int) -> Item? {
        return item(atIndexPath: NSIndexPath(forRow: row, inSection: section))
    }

    /// :nodoc:
    public func headerTitle(inSection section: Int) -> String? {
        guard section < numberOfSections() else { return nil }
        return self.fetchedResultsController.sections?[section].name
    }

    /// :nodoc:
    public func footerTitle(inSection section: Int) -> String? {
        return nil
    }
}

```

**Comment by colinmorelli** [comment]
Correction to myself above: it doesn't quite preserve exact behavior since implementations will be dependent on that class subclassing NSFetchedResultsController...any other thoughts?

**Comment by jessesquires** [comment]
Thanks @colinmorelli ! 😄 

In Swift 2.3/3.0 the new SDK overlays add lightweight generics to `NSFetchedResultsController`. 

In a previous beta (can't remember which), I tried using `NSFRC` directly but ran into issues because ObjC lightweight generics are so limited. I haven't tried this again with the most recent beta, but I doubt it is much different.

Does `CoreStore` provide any kind of "escape hatch" to get a context? 

---

You could also try https://github.com/jessesquires/JSQCoreDataKit 😉

**Comment by colinmorelli** [comment]
@jessesquires - makes sense. Unfortunately, CoreStore doesn't provide direct access to the context (his goal is to try to safeguard the thread management strategies of `NSManagedObjectContext` and preventing direct access to the contexts admittedly does prevent a whole class of issues) - though I think with compelling enough reasons it _could_ be done.

However, I still feel that the requirement that JSQ directly instantiate the `NSFetchedResultsController` is still going to be limiting for certain applications. For example, even without CoreStore, my application is structured in such a way that the VCs don't touch contexts directly, but rather do so through services. Those services would now need to become aware of JSQ, which is something I'd ideally like to keep up in the UI.

From looking at the implementation of the protocol in the FRC, it seems like it's just doing a forced downcast to the generic type (understandable - you don't have another choice). Given that, there's no real way for the library to enforce type safety anyway (it's all going to be a runtime check). I'd still (personally) lean towards having the FRC implementation of DataSourceProtocol allow the user to provide a custom FRC.

P.S. - your core data abstraction was one I looked at when comparing options. However, I ended up settling on CoreStore because the way it looks at "transactions" (instead of contexts) makes the insanity of CD much easier to reason about. It does have some drawbacks, of course, but it might spark some more ideas for your own library!

**Comment by jessesquires** [comment]
I just tried this again. Attempting to make `NSFetchedResultsController` conform to `DataSourceProtocol` seg faults the compiler 😢

**Comment by colinmorelli** [comment]
Well _that's_ not a good excuse. Breathing the wrong direction segfaults the swift compiler ;).

**Comment by colinmorelli** [comment]
I don't think you necessarily need to make NSFetchedResultsController conform directly to the protocol though. Why not keep the existing FetchedResultsController class to implement the protocol which takes (and holds via strong ref) a FRC in its constructor. It can also set FRC.delegate = self, and expose its own delegate instance which the `delegateProvider.tableDelegate` can listen to.

Edit: this does mean that you'll have to go through an extra layer of indirection to get to the raw FRC you provided to the data source (something like `dataSource.fetchedResultsController`), but the `DataSourceProtocol` implements everything people would care about on the FRC anyway, and does so with an API that most would prefer, so I don't see this being much of a problem in practice.

**Comment by jessesquires** [comment]
Just looked at this again. 

Conclusion:

- Trying to make `NSFetchedResultsController` conform to `DataSourceProtocol` still results in the following error:
```
Extension of a generic Objective-C class cannot access the class's generic parameters at runtime
```
I doubt this will ever change.

- I think subclassing is the best solution here, not injecting your own `NSFetchedResultsController` and forwarding methods -- that's too much boilerplate and maintenance. They way this is written now, clients can easily just drop the `NS` prefix and everything works. Clients shouldn't be subclassing `NSFetchedResultsController`, but if they are, it's still a minor change to inherit from ours instead.
