### ISSUE TITLE
FetchedResultsController/CollectionView did update hook?

### ISSUE THREAD

**Issue by arthurhammer** [jessesquires/JSQDataSourcesKit#70]
I'm looking for a hook for when the fetched results controller has updated data and/or the collection view did finish animating ([performing batch updates](https://github.com/jessesquires/JSQDataSourcesKit/blob/7b069c235a8015f470b71ab99c8ce703414f0206/Source/FetchedResultsDelegate.swift#L127)).

**Use case**: In the example project ([right around here](https://github.com/jessesquires/JSQDataSourcesKit/blob/7b069c235a8015f470b71ab99c8ce703414f0206/Example/Sources/FetchedCollectionViewController.swift#L139)) in the view controller, I want to wait till the collection view has animated in the new cell and then perform a segue from it. Or do some other stuff with the cell. As it is now, the segue would be performed immediately without waiting for the animation to finish. 

Ideas how to solve this with `JSQDataSourcesKit` or rethink what I'm trying to do?

**Comment by jessesquires** [comment]
Thanks @arthurhammer ! 😄 

I'm not sure I understand your use case. What do you need to animate?
