### ISSUE TITLE
Cell factory dependency in FetchedResultsDelegateProvider?

### ISSUE THREAD

**Issue by arthurhammer** [jessesquires/JSQDataSourcesKit#71]
I'm currently looking at `FetchedResultsDelegateProvider` and wondering two things:
#### 1

Why is a cell factory needed for `FetchedResultsDelegateProvider`?

[It is used only to update a cell](https://github.com/jessesquires/JSQDataSourcesKit/blob/406cdfa9f460da861c191e751e605ab0978428bf/Source/FetchedResultsDelegate.swift#L143-L148). Can't [`reloadItems(at:)`](https://developer.apple.com/reference/uikit/uicollectionview/1618055-reloaditems) be used instead? #32 mentions this might be an issue for sections but I'm not confident if this applies to cells.

Conceptually, I think `FetchedResultsDelegate/Provider` shouldn't need to know about cell creation.
#### 2

Can't the [`objectChanges`](https://github.com/jessesquires/JSQDataSourcesKit/blob/406cdfa9f460da861c191e751e605ab0978428bf/Source/FetchedResultsDelegate.swift#L60) tracking be replaced by closures? Sketch:

```
typealias ObjectChange = () -> ()
var objectChanges = [ObjectChange]()
...

case .insert:
   if let insertIndexPath = newIndexPath {
      self.objectChanges.append {
          self.collectionView?.insertItems(at: [insertIndexPath])
      }
...

func applyObjectChanges() {
    objectChanges.forEach { $0() }
}
```

This would avoid duplication of the type switches.

**Comment by jessesquires** [comment]
Thanks @arthurhammer ! 😄 

> 1

Correct. `reloadItems(at:)` or `reloadSections(:)` is simply a "delete, then insert" under the hood, which can cause some inconsistency and animation issues. Also see [Apple's example](https://developer.apple.com/reference/coredata/nsfetchedresultscontrollerdelegate) for the FRC delegate boilerplate.

> 2 

Yeah! 👍 That seems reasonable. Good idea 👌
