### ISSUE TITLE
Add docs for TableEditingController

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQDataSourcesKit#78]
Follow up from #67. 

We need to add docs to the new `TableEditingController`.

https://github.com/jessesquires/JSQDataSourcesKit/blob/develop/Source/TableEditingController.swift

**Comment by jessesquires** [comment]
cc @psartzetakis 😄

**Comment by psartzetakis** [comment]
I will take care of it 😄

**Comment by psartzetakis** [comment]
@jessesquires , apologies but I haven't done that before. Would you mind giving some pointers / tips ? Do I have just to add `comments` in the source file?

**Comment by jessesquires** [comment]
Hey @psartzetakis - no problem! 😄 

Yeah, that's all it is — just comments. Just follow the existing examples and feel free to comment here if you have any questions. (Or we can talk on the PR, too)
