### ISSUE TITLE
Implement data source insert convenience methods

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQDataSourcesKit#79]
In #67 we added some convenience methods to `DataSource` to remove items.

Let's add similar methods to insert.

https://github.com/jessesquires/JSQDataSourcesKit/blob/develop/Source/DataSource.swift#L166-L189

Tasks:

- Add 2 new methods, one with `(row, section)` and one with `IndexPath`
- Add docs
- Add unit tests

**Comment by jessesquires** [comment]
cc @psartzetakis  😊

**Comment by psartzetakis** [comment]
I will take care of it 😄

**Comment by jessesquires** [comment]
@psartzetakis -- By the way, there's no pressure here! Don't feel like you have to do any of these new tasks if you don't want to. 😄 

I just wanted to let you know about them. 😊

**Comment by psartzetakis** [comment]
Yeah sure, I am aware of that.  😊

**Comment by psartzetakis** [comment]
Hi @jessesquires , 

I have a question here. Let's assume that we have 2 sections (`section-0`, `section-1`).
If the user wants to add an item in `section-2` which strategy do we follow?

1. We are not allow the creation of the new section so nothing happens? (kind of restrictive)
2. We create a new section if it doesn't exist. Which leads to the following question:

- if the users requests `section-2` it kind of makes sense to add it, but what if he requests `section-5`? Do we ignore his preference for `section-5` and we create the `section-2` instead?

**Comment by jessesquires** [comment]
@psartzetakis 

Let's mimic the `Array` APIs, you can't insert out-of-bounds. That will keep it simple for now. 👍
