### ISSUE TITLE
Package is fixed dependent on libswiftCoreData.dylib

### ISSUE THREAD

**Issue by dolfs** [jessesquires/JSQDataSourcesKit#90]
When using this without using the CoreData related parts (which can still be quite useful), you get an error at runtime:
```
dyld: Library not loaded: @rpath/libswiftCoreData.dylib
  Referenced from: /Users/dolf/Documents/Dough/DoughMaster/Carthage/Build/iOS/JSQDataSourcesKit.framework/JSQDataSourcesKit
  Reason: image not found
```

It should be possible without including this library to keep binary size optimized.

**Comment by jessesquires** [comment]
Thanks @dolfs !

How are you installing the library? via CocoaPods, or... ?

**Comment by dolfs** [comment]
Carthage.
The cause seems to be the inclusion of CoreData as a framework in the pod spec. I think it can be left out in the sense that if a user wants to use the FetchedResultsController aspect, they must already be using CoreData in their project, and thus the requirement to include that framework would be on their own project already.

**Comment by jessesquires** [comment]
> The cause seems to be the inclusion of CoreData as a framework in the pod spec.

This shouldn't have any affect on Carthage. Carthage doesn't know or care about pod specs.

**Comment by jessesquires** [comment]
My guess is that Carthage knows `import CoreData` exists for parts of this lib.

I don't think there's much we can do here -- a *very long term* goal would be to breakout the CoreData parts into a new library. 😞 

going to close this for now.
